$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$matrix=Get-Content -Raw (Join-Path $root 'baseline\game004_asset_matrix.json') -Encoding UTF8|ConvertFrom-Json
$out=Join-Path $root 'handoff\asset_production_v001';New-Item -ItemType Directory -Force $out|Out-Null
$packMap=@{}
foreach($op in $matrix.opportunities){$pack=[string]$op.game_pack_id;if(!$packMap.ContainsKey($pack)){$packMap[$pack]=@()};$packMap[$pack]+=$op.opportunity_id}
$items=@();foreach($op in $matrix.opportunities){$items += [ordered]@{game_pack_id=$op.game_pack_id;opportunity_id=$op.opportunity_id;l_level=$op.l_level;frozen_content=$op.frozen_content;asset_status='unproduced';required_layers=$op.required_layers}}
$manifest=[ordered]@{schema_version='game004-asset-production-manifest-v1';baseline_version='GAME004-BASELINE-V1';source_matrix_sha256=$matrix.source_sha256;opportunity_count=$matrix.opportunity_count;status='production_planned';rights_status='unknown';approval_policy='candidate -> processed -> approved; no automatic approval';layers=@('target','contrast_or_distractor','region','rule_or_example','natural_outcome','neutral_buffer','low_sensory_variant','rights_record');pack_ids=@($packMap.Keys);opportunities=$items}
$manifest|ConvertTo-Json -Depth 12|Set-Content (Join-Path $out 'GAME004_ASSET_MASTER_MANIFEST_V1.json') -Encoding UTF8
@('# GAME-004 ASSET HANDOFF V1','','FACT SOURCES: PROJECT_BASELINE.md and baseline/game004_content_baseline.json.','Status: production_planned. All assets follow candidate -> processed -> approved. L5 rights remain unknown until authorized.','Existing Atlas/Qwen object art is candidate only. Programmatic region/outcome art is technical placeholder only. XYQ production was not executed because XYQ_ACCESS_KEY is missing.')|Set-Content (Join-Path $out 'GAME004_ASSET_HANDOFF_V1.md') -Encoding UTF8
@('# GAME-004 ASSET BATCH PLAN V1','','B01: habitat shell, regions, outcomes, neutral buffer.','B02: L1 shape/color/exact-match assets.','B03: L2 single-attribute/size/function assets.','B04: L3 novel instances/rule switching/hierarchy.','B05: L4 irrelevant-feature interference and 3-4 regions.','B06: L5 authorized photo containers and life bridge.','B07: all low-sensory variants, examples, recovery states.')|Set-Content (Join-Path $out 'GAME004_ASSET_BATCH_PLAN_V1.md') -Encoding UTF8
@('# GAME-004 DEEPSEEK HANDOFF CHECKLIST V1','','- Read the master manifest without changing frozen_content.','- Load only approved assets into the final runtime.','- Validate all required layers per opportunity.','- Keep L5 inactive without rights approval.','- Preserve asset_id, opportunity_id, game_pack_id and source traceability.','- Real App host and real child/user testing remain unverified.')|Set-Content (Join-Path $out 'GAME004_DEEPSEEK_HANDOFF_CHECKLIST.md') -Encoding UTF8
Write-Host "ASSET_HANDOFF_BUILD_PASS opportunities=$($matrix.opportunity_count) packs=$($packMap.Count)"
